### ISSUE TITLE
Warnung im Debug Modus Fehler im Validator

### ISSUE THREAD

**Issue by pbd-kn** [markocupic/fontawesome-icon-picker-bundle#4]
Hi Marko,

ich habe das mal eingebaut. In der Produktionsumgebung bekomme ich die Icons angezeigt.
Im Debug kommt die Warnung 
Warning: Attempt to read property "faIcon" on null
in[ C:\wampneu\www\co4\websites\co4raw\vendor\markocupic\fontawesome-icon-picker-bundle\src\ContaoBackendWidget\FontawesomeIconPicker.php ](http://co4raw.local/_profiler/open?file=vendor\markocupic\fontawesome-icon-picker-bundle\src\ContaoBackendWidget\FontawesomeIconPicker.php&line=54#line54)(line 54)

            $arrIconsAll = $iconUtil->getIconsAll();
            $varValue = '';
            $selectedIcon = null;
            $selectedIconPrefix = null;
            $arrIcon = StringUtil::deserialize($model->faIcon);
            $arrIcons = [];
            if (!empty($arrIcon) && \is_array($arrIcon)) {
                $varValue = implode('||', StringUtil::deserialize($model->faIcon, true));

Im Produktionsmodus bekomme ich einen Fehler aus dem Validator geliefert.
[2023-07-17T11:57:19.347301+00:00] request.CRITICAL: Uncaught PHP Exception TypeError: "explode(): Argument #2 ($string) must be of type string, null given" at C:\wampneu\www\co4\websites\co4raw\vendor\markocupic\fontawesome-icon-picker-bundle\src\ContaoBackendWidget\FontawesomeIconPicker.php line 111 {"exception":"[object] (TypeError(code: 0): explode(): Argument #2 ($string) must be of type string, null given at C:\\wampneu\\www\\co4\\websites\\co4raw\\vendor\\markocupic\\fontawesome-icon-picker-bundle\\src\\ContaoBackendWidget\\FontawesomeIconPicker.php:111)"} []

    protected function validator(mixed $varInput): mixed
    {
        $varInput = explode('||', $varInput);
        $varInput = serialize($varInput);

        return parent::validator($varInput);
    }

Mache ich irgendwo etwas falsch

Mein dca Field      
'fontawesomeIconPicker' => [
            'label' => 'fontawesomeIconPicker',
            'inputType' => 'fontawesomeIconPicker',
            'sql' => "varchar(255) NOT NULL default ''",
        ],
Mein Icon-Fenster sieht so aus das icon 500px habe ich ausgewählt.

Der Fehler tritt auff, wenn ich abspeichere
![grafik](https://github.com/markocupic/fontawesome-icon-picker-bundle/assets/75879364/6e2646bc-d4a5-4dca-a3ee-797f26d06e9e)

LG
Peter

**Comment by pbd-kn** [comment]
das ändert nichts mein dca ist nun
        'fontawesomeIconPicker' => [
            'label' => 'fontawesomeIconPicker',
            'inputType' => 'fontawesomeIconPicker',
            'sql'       => 'blob NULL',
        ],

Beim Speichern Fehler in Zeile 111 bei Validate
request.CRITICAL: Uncaught PHP Exception TypeError: "explode(): Argument https://github.com/markocupic/fontawesome-icon-picker-bundle/pull/2 ($string) must be of type string, null given" at C:\wampneu\www\co4\websites\co4raw\vendor\markocupic\fontawesome-icon-picker-bundle\src\ContaoBackendWidget\FontawesomeIconPicker.php line 111 {"exception":"[object] (TypeError(code: 0): explode(): Argument https://github.com/markocupic/fontawesome-icon-picker-bundle/pull/2 ($string) must be of type string, null given at C:\wampneu\www\co4\websites\co4raw\vendor\markocupic\fontawesome-icon-picker-bundle\src\ContaoBackendWidget\FontawesomeIconPicker.php:111)"}



im Debugmode der Abbruch mit der Warnung beim Öffen zeile 54
        $arrIcon = StringUtil::deserialize($model->faIcon);
Warning: Attempt to read property "faIcon" on null
in[ C:\wampneu\www\co4\websites\co4raw\vendor\markocupic\fontawesome-icon-picker-bundle\src\ContaoBackendWidget\FontawesomeIconPicker.php ](http://co4raw.local/_profiler/open?file=vendor%5Cmarkocupic%5Cfontawesome-icon-picker-bundle%5Csrc%5CContaoBackendWidget%5CFontawesomeIconPicker.php&line=54#line54)(line 54)
ich nehme an die Zeile 43 liefert Null

**Comment by markocupic** [comment]
Hallo Peter 

 

Sollte nun behoben sein.

 

Lg Marko
 

--------------------------------------
Marko Cupic
Surenweidstr. 2
CH-6208 Oberkirch

http://4ae-racing-team.ch
http://kletterkader.com

 
 

Gesendet: Montag, 17. Juli 2023 um 14:36 Uhr
Von: "pbd-kn" ***@***.***>
An: "markocupic/fontawesome-icon-picker-bundle" ***@***.***>
Cc: "Subscribed" ***@***.***>
Betreff: [markocupic/fontawesome-icon-picker-bundle] Warnung im Debug Modus Fehler im Validator (Issue #4)


 

Hi Marko,

ich habe das mal eingebaut. In der Produktionsumgebung bekomme ich die Icons angezeigt.
Im Debug kommt die Warnung
Warning: Attempt to read property "faIcon" on null
in C:\wampneu\www\co4\websites\co4raw\vendor\markocupic\fontawesome-icon-picker-bundle\src\ContaoBackendWidget\FontawesomeIconPicker.php (line 54)

        $arrIconsAll = $iconUtil->getIconsAll();
        $varValue = '';
        $selectedIcon = null;
        $selectedIconPrefix = null;
        $arrIcon = StringUtil::deserialize($model->faIcon);
        $arrIcons = [];
        if (!empty($arrIcon) && \is_array($arrIcon)) {
            $varValue = implode('||', StringUtil::deserialize($model->faIcon, true));


Im Produktionsmodus bekomme ich einen Fehler aus dem Validator geliefert.
[2023-07-17T11:57:19.347301+00:00] request.CRITICAL: Uncaught PHP Exception TypeError: "explode(): Argument #2 ($string) must be of type string, null given" at C:\wampneu\www\co4\websites\co4raw\vendor\markocupic\fontawesome-icon-picker-bundle\src\ContaoBackendWidget\FontawesomeIconPicker.php line 111 {"exception":"[object] (TypeError(code: 0): explode(): Argument #2 ($string) must be of type string, null given at C:\wampneu\www\co4\websites\co4raw\vendor\markocupic\fontawesome-icon-picker-bundle\src\ContaoBackendWidget\FontawesomeIconPicker.php:111)"} []

protected function validator(mixed $varInput): mixed
{
    $varInput = explode('||', $varInput);
    $varInput = serialize($varInput);

    return parent::validator($varInput);
}


Mache ich irgendwo etwas falsch

Mein dca Field
'fontawesomeIconPicker' => [
'label' => 'fontawesomeIconPicker',
'inputType' => 'fontawesomeIconPicker',
'sql' => "varchar(255) NOT NULL default ''",
],
Mein Icon-Fenster sieht so aus das icon 500px habe ich ausgewählt.

Der Fehler tritt auff, wenn ich abspeichere


LG
Peter

**Comment by pbd-kn** [comment]
Danke,
schön dasssa uch der Fehler zugriff auf contenmodel->faicon behoben ist
